spring:
  application:
    name: STP
fx:
  TITLE: STP
  WIDTH: 800
  HEIGHT: 600
  SIZE_ROUTER: 10
  TIME_ANIMATION: 500
  WIDTH_LINE: 2
  WIDTH_OFF_LINE: 4
  WIDTH_DOTTED_LINE: 3
text:
  ADD_NODE: "Добавьте узлы коммутаторы"
  NEXT: "Следующий этап"
  NEXT_STEP: "Следующий шаг"
  LEN_TO_ROOT: "Расстояние до корня: "
  IS_ROOT: "корневой"
  IS_NOT_ROOT: "не корневой"
int:
  MAX: 2147483647
